### ISSUE TITLE
Create current-state documentation for topics

### ISSUE THREAD

**Issue by dominikhorn93** [it-at-m/digiwf-project#144]

**Comment by lmoesle** [comment]
**Todos from PR-Feedback (https://github.com/it-at-m/digiwf-asyncapi-docs-starter/pull/1)**

- Annotations on Methods instead of classes
- Don't hardcode kafka (enable usage of different spring-cloud-stream-binders)
- Allow function router usage (maybe provide a dedicated scanner for function routers)
